name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denolib/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno Generated Files
        uses: actions/cache@v1
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-cache-${{ hashFiles('**/mod.ts') }}

      - name: Format
        run: deno task fmt

      - name: Tests
        run: deno task test

      - name: Lint
        run: deno task lint

      - name: Coverage
        run: deno task cov > cov.lcov